export class Response {
    static HTTP_CONTINUE: number = 100;
    static HTTP_SWITCHING_PROTOCOLS: number = 101;
    static HTTP_PROCESSING: number = 102;            // RFC2518
    static HTTP_EARLY_HINTS: number = 103;           // RFC8297
    static HTTP_OK: number = 200;
    static HTTP_CREATED: number = 201;
    static HTTP_ACCEPTED: number = 202;
    static HTTP_NON_AUTHORITATIVE_INFORMATION: number = 203;
    static HTTP_NO_CONTENT: number = 204;
    static HTTP_RESET_CONTENT: number = 205;
    static HTTP_PARTIAL_CONTENT: number = 206;
    static HTTP_MULTI_STATUS: number = 207;          // RFC4918
    static HTTP_ALREADY_REPORTED: number = 208;      // RFC5842
    static HTTP_IM_USED: number = 226;               // RFC3229
    static HTTP_MULTIPLE_CHOICES: number = 300;
    static HTTP_MOVED_PERMANENTLY: number = 301;
    static HTTP_FOUND: number = 302;
    static HTTP_SEE_OTHER: number = 303;
    static HTTP_NOT_MODIFIED: number = 304;
    static HTTP_USE_PROXY: number = 305;
    static HTTP_RESERVED: number = 306;
    static HTTP_TEMPORARY_REDIRECT: number = 307;
    static HTTP_PERMANENTLY_REDIRECT: number = 308;  // RFC7238
    static HTTP_BAD_REQUEST: number = 400;
    static HTTP_UNAUTHORIZED: number = 401;
    static HTTP_PAYMENT_REQUIRED: number = 402;
    static HTTP_FORBIDDEN: number = 403;
    static HTTP_NOT_FOUND: number = 404;
    static HTTP_METHOD_NOT_ALLOWED: number = 405;
    static HTTP_NOT_ACCEPTABLE: number = 406;
    static HTTP_PROXY_AUTHENTICATION_REQUIRED: number = 407;
    static HTTP_REQUEST_TIMEOUT: number = 408;
    static HTTP_CONFLICT: number = 409;
    static HTTP_GONE: number = 410;
    static HTTP_LENGTH_REQUIRED: number = 411;
    static HTTP_PRECONDITION_FAILED: number = 412;
    static HTTP_REQUEST_ENTITY_TOO_LARGE: number = 413;
    static HTTP_REQUEST_URI_TOO_LONG: number = 414;
    static HTTP_UNSUPPORTED_MEDIA_TYPE: number = 415;
    static HTTP_REQUESTED_RANGE_NOT_SATISFIABLE: number = 416;
    static HTTP_EXPECTATION_FAILED: number = 417;
    static HTTP_I_AM_A_TEAPOT: number = 418;                                               // RFC2324
    static HTTP_MISDIRECTED_REQUEST: number = 421;                                         // RFC7540
    static HTTP_UNPROCESSABLE_ENTITY: number = 422;                                        // RFC4918
    static HTTP_LOCKED: number = 423;                                                      // RFC4918
    static HTTP_FAILED_DEPENDENCY: number = 424;                                           // RFC4918
    static HTTP_RESERVED_FOR_WEBDAV_ADVANCED_COLLECTIONS_EXPIRED_PROPOSAL: number = 425;   // RFC2817
    static HTTP_TOO_EARLY: number = 425;                                                   // RFC-ietf-httpbis-replay-04
    static HTTP_UPGRADE_REQUIRED: number = 426;                                            // RFC2817
    static HTTP_PRECONDITION_REQUIRED: number = 428;                                       // RFC6585
    static HTTP_TOO_MANY_REQUESTS: number = 429;                                           // RFC6585
    static HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE: number = 431;                             // RFC6585
    static HTTP_UNAVAILABLE_FOR_LEGAL_REASONS: number = 451;
    static HTTP_INTERNAL_SERVER_ERROR: number = 500;
    static HTTP_NOT_IMPLEMENTED: number = 501;
    static HTTP_BAD_GATEWAY: number = 502;
    static HTTP_SERVICE_UNAVAILABLE: number = 503;
    static HTTP_GATEWAY_TIMEOUT: number = 504;
    static HTTP_VERSION_NOT_SUPPORTED: number = 505;
    static HTTP_VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL: number = 506;                        // RFC2295
    static HTTP_INSUFFICIENT_STORAGE: number = 507;                                        // RFC4918
    static HTTP_LOOP_DETECTED: number = 508;                                               // RFC5842
    static HTTP_NOT_EXTENDED: number = 510;                                                // RFC2774
    static HTTP_NETWORK_AUTHENTICATION_REQUIRED: number = 511;
}
